### ISSUE TITLE
FSD作者你好，你引用的工作内容为抄袭

### ISSUE THREAD

**Issue by MaxMax2016** [xieyuankun/FSD-Dataset#1]
具体如下：
https://github.com/svc-develop-team/so-vits-svc/tree/4.1-Stable/vdecoder/hifiganwithsnake/alias
这部分代码抄袭于
https://github.com/PlayVoice/so-vits-svc-5.0/tree/bigvgan-mix-v2/vits_decoder/alias

两个项目为竞争项目，所以so-vits-svc刻意隐瞒了代码出处，并一本正经的将bigvgan称为hifiganwithsnake。bigvgan为行业知名项目，您可以对比snake和bigvgan的代码差异。

而FSD论文中，对它的这部分工作进行的详细分析、也回避了：hifiganwithsnake就是bigvgan这一事实。

**Comment by MaxMax2016** [comment]
![bigvgan](https://github.com/xieyuankun/FSD-Dataset/assets/16432329/2b7b4db5-f42f-424a-8750-5aa65cdae91e)

**Comment by xieyuankun** [comment]
您好，感谢您对我们工作的关注。
我已在您的公众号上进行了回复，希望进一步交流。

**Comment by MaxMax2016** [comment]
您好，我没收到您的回复

**Comment by xieyuankun** [comment]
那我就在这里回复您吧。

我们这篇文章是专注于歌声鉴伪的，使用了一些主流的歌声伪造方法制作虚假歌声，以便检测。我在F02这里使用了https://github.com/svc-develop-team/so-vits-svc里面名为NSF-SNAKE-HIFIGAN的声码器进行生成，我在论文里那段只是对这项方式的客观描述。至于是否是先于别人，还是他自己提出的这点，我们做数据集时并没有关注这点，只按照最流行的项目（收藏标星数）进行复现。

如果他侵犯了您的代码独创权益，强烈建议您去他的git下面发声维权。您的工作或是svc-develop-team的，我并没有看到有先后的刊载论文或arxiv能体现时间，我引用svc devlop team的工作是因为我们确实是使用他的框架进行合成的。在第二章节方法描述中，我对使用的F02进行了实验方法的客观描述。我觉得我们是无辜的，我们只是想验证目前语音鉴伪模型是否在歌声鉴伪任务上有效。不应该卷入您两个团队间的所谓的竞争内斗。

另外BigVGAN确实是最先结合snake与hifigan的。但涉及抄袭的这部分包括NSF+SNAKE+HIFIGAN相对于BigVGAN其实是更进一步并应用在SVC任务中，因下游任务不同并且还有小幅更改，所以其实算做新的工作。从时间上来说确实也是您的发布时间优先，但我目前未发现相关论文能引。所以您这边想如何解决该问题？在F02处引出您这边项目的链接表明？

我昨天于您的公众号也进行了回复，但截至目前尚未收到回复，该篇文章对本人造成了负面影响，希望能进一步沟通。

因为该论文已提交arxiv，但未经过专家评审，所有问题栏将于几天后关闭，等待专家评审。

如果您有后续问题，请联系邮箱xieyuankun@cuc.edu.cn，欢迎随时交流。

FSD第一作者-谢元坤

**Comment by MaxMax2016** [comment]
```
所以您这边想如何解决该问题？在F02处引出您这边项目的链接？
```
如果您不想引用我的项目，那就删除涉及抄袭的部分

**Comment by MaxMax2016** [comment]
```
但涉及抄袭的这部分包括NSF+SNAKE+HIFIGAN相对于BigVGAN其实是更进一步并应用在SVC任务中，因下游任务不同并且还有小幅更改，所以其实算做新的工作。从时间上来说确实也是您的发布时间优先，但我目前未发现相关论文能引。
```
亲爱的作者你看看这个是什么，注意看时间
https://github.com/PlayVoice/NSF-BigVGAN/tree/main/model/alias

**Comment by MaxMax2016** [comment]
这是BIGVGAN
![QQ浏览器截图20230908134000](https://github.com/xieyuankun/FSD-Dataset/assets/16432329/65b2ad83-9186-435e-8683-fdb1f0e15e99)
这是NSF-BIGVGAN相关论文
![QQ浏览器截图20230908134025](https://github.com/xieyuankun/FSD-Dataset/assets/16432329/fcf8eb76-6d1c-402b-8f6b-9b838437a076)

**Comment by xieyuankun** [comment]
> ```
> 但涉及抄袭的这部分包括NSF+SNAKE+HIFIGAN相对于BigVGAN其实是更进一步并应用在SVC任务中，因下游任务不同并且还有小幅更改，所以其实算做新的工作。从时间上来说确实也是您的发布时间优先，但我目前未发现相关论文能引。
> ```
> 
> 亲爱的作者你看看这个是什么，注意看时间 https://github.com/PlayVoice/NSF-BigVGAN/tree/main/model/alias

我这不是说你的发布时间优先了吗？但你的NSF+SNAKE+HIFIGAN你并没有发表论文，我只看到https://github.com/PlayVoice/NSF-BigVGAN/tree/main/model/alias，所以说没有你的论文能引用有问题吗？

**Comment by MaxMax2016** [comment]
SO-VITS-SVC有论文吗？为啥被引用？抄袭的也能被引用？

**Comment by xieyuankun** [comment]
> SO-VITS-SVC有论文吗？为啥被引用？抄袭的也能被引用？

我用他的代码生成的数据，我得引出处啊。

**Comment by MaxMax2016** [comment]
他的代码拷贝的我的呀？

**Comment by MaxMax2016** [comment]
建议删除这部分

**Comment by xieyuankun** [comment]
这个您得到他那边说拷贝的事，我只是选择了一个其中一个implement做实验

**Comment by MaxMax2016** [comment]
没事，你按的客观来，甚至不管是不是抄袭，我也按我的客观进行公开这件事。

**Comment by xieyuankun** [comment]
ok，那先这样吧，等专家评审，很遗憾没用您这边的so-vits做实验引发这么多不愉快，也祝您科研工作顺利。

**Comment by MaxMax2016** [comment]
祝您的文章一定要被录用，没录用曝光都没意思
